server:
  port: ${myapp.port:8989}

spring:
  datasource:

    url: jdbc:mariadb://localhost:3306/board_study
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true
        "[user_sql_comments]": true
        "[highlight_sql]": true
        "[hbm2ddl.auto]": create

    open-in-view: false
    show-sql: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug

    board example:
      board: info